### ISSUE TITLE
gpu memory leak

### ISSUE THREAD

**Issue by sukibean163** [deepinsight/mxnet-mtcnn#6]
gpu memory leak

**Comment by taoxunqiang** [comment]
Dear @sukibean163,

   I also met this problem. Had you solved it?

Best wishes,
Tao Xunqiang

**Comment by sukibean163** [comment]
@taoxunqiang ,hi! try to MXPredFree correctly for p/r/o net

**Comment by taoxunqiang** [comment]
Dear @sukibean163,

Thank you for quick reply.
I will try it.

Best wishes,
